backend:
  name: git-gateway
  branch: decap # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - label: "People"
    name: "people"
    folder: "_people"
    create: true
    slug: "{{first}}-{{last}}"
    identifier_field: last
    fields:
      - {label: "First name", name: "first", widget: "string"}
      - {label: "Last name", name: "last", widget: "string"}
      - {label: "Display name", name: "displayname", widget: "string", hint: "This is how your name will show up under your photo on the People page - generally your preferred first and last name, followed by any degrees, e.g. \"Miranda Lim, MD, PhD\""}
      - {label: "SHARP role", name: "role", widget: "string"}
      - {label: "Preferred pronouns", name: "pronouns", widget: select, options: ["she/hers", "he/his", "they/theirs"], default: null, hint: "You can leave this blank to omit."}
      - {label: "Photo", name: "photo", widget: image, hint: "For best results, photos should be square, no larger than 500 KB, and at least 200px by 200px in dimensions.", allow_multiple: false, default: "/images/profile-placeholder.png", media_folder: "/images/people"}
      - {label: "Google Scholar URL (Optional)", name: "googlescholar", widget: string, required: false}
      - {label: "PubMed URL (Optional)", name: "googlescholar", widget: string, required: false}
      - {label: "Bio", name: "body", widget: "markdown", required: false}
  - label: "Site data"
    name: "Site data"
    files:
    - label: "External Links"
      name: "ext-resources"
      file: _data/ext-resources.yml
      create: true
      fields:
        - label: resource
          name: resource
          widget: list
          fields:
            - {label: "Name", name: title, widget: string}
            - {label: URL, name: url, widget: string}
    - label: "Press & Media"
      name: media
      file: _data/media.yml
      create: true
      fields:
        - label: "Media items"
          name: media
          widget: list
          fields: 
            - {label: "title", name: "title", widget: "string"}
            - {label: "Media type", name: "type", widget: select, options: ["article", "podcast", "award", "video"] }
            - {label: "Description (optional)", name: "description", widget: markdown, default: null}
            - {label: "Source", name: "source", widget: "string", hint: "The name of the host website, magazine, journal, podcast, award-granting institution, etc."}
            - {label: "Month of publication", name: "month", widget: "select", options: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]}
            - {label: "Year of publication", name: "year", widget: "string"}
            - {label: "URL", name: "url", widget: string}
            - {label: "Feature on homepage?", name: "featured", widget: "boolean", default: false}
            - {label: "Homepage headline", name: "headline", widget: "markdown", hint: "Only necessary if above is marked 'true'. Limit to around ~150 characters.", default: null}
            - {label: "Button text", name: "button-text", widget: "string", hint: "This is optional. Use to override the 'Read', 'Watch', 'Listen' defaults.", default: null}
    - label: "Publications"
      name: "publications"
      file: "_data/publications.yml"
      create: true
      fields:
        - label: publications
          name: publications
          widget: list
          fields:
            - {label: "Title", name: title, widget: string}
            - {label: "Citation", name: citation, widget: markdown, hint: "For consistency, use Vancouver citation formatting."}
            - {label: "Summary", name: summary, widget: text}
            - {label: "DOI URL", name: doi, widget: string}
            - {label: "Image", name: image, widget: image, allow_multiple: false, media_folder: /images/publications, default: "/images/sharperwave.png"}
    - label: "Research Studies"
      name: "studies"
      file: "_data/studies.yml"
      create: true
      fields:
        - label: studies
          name: studies
          widget: list
          fields:
            - {label: "Study name", name: "title", widget: "string"}
            - {label: "URL", name: url, widget: "string"}
            - {label: "Button text", name: "button-text", widget: "string"}
            - {label: "Flyer or other image", name: "image", widget: "image", allow_multiple: false, media_folder: "/images/research_studies", default: "/images/sharperwave.png"}
    - label: "Research studies FAQ"
      name: "faq-studies"
      file: "_data/studies-faq.yml"
      create: true
      fields:
        - label: faq
          name: faq
          widget : list
          fields: 
            - {label: "Question", name: "question", widget: "markdown"}
            - {label: "Answer", name: "answer", widget: "markdown"}
    - label: "Join the Lab FAQ"
      name: "faq-lab"
      file: "_data/lab-faq.yml"
      create: true
      fields:
        - label: faq
          name: faq
          widget : list
          fields: 
            - {label: "Question", name: "question", widget: "markdown"}
            - {label: "Answer", name: "answer", widget: "markdown"}