backend:
  name: git-gateway
  branch: decap # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - label: "Global"
    name: "global"
    files:
    - label: "External Links"
      name: "ext-resources"
      file: "_data/ext-resources.yml"
      create: true
      fields:
        - label: resource
          name: resource
          widget: list
          fields:
            - {label: "Name", name: title, widget: string}
            - {label: URL, name: url, widget: string}
    - label: "Publications"
      name: "publications"
      file: "_data/publications.yml"
      create: true
      fields:
        - label: publications
          name: publications
          widget: list
          fields:
            - {label: "Title", name: title, widget: string}
            - {label: "Citation", name: citation, widget: string}
            - {label: "Summary", name: summary, widget: string}
            - {label: "DOI URL", name: doi, widget: string}
            - {label: "Image", name: image, widget: image}